### ISSUE TITLE
Move project to jazzband

### ISSUE THREAD

**Issue by jwhitlock** [jazzband/django-nose#261]
[Jazzband](https://jazzband.co) is a project to share responsibility for administration of open source projects. django-nose is a good candidate because:
1. The project is mature and widely used. It is part of the workflow of mature projects, and is often picked because it is the "boring" choice.
2. Community attention is on [py.test](http://pytest.org/latest/), which is gaining plugins and features. This is reflected in the bug-to-PR ratio in the issue tracker (many bug reports, fewer PRs).
3. The project has been maintained by Mozilla developers. Out of the "Maintainer" list in AUTHORS.rst, only one (me) is actually active. Mozilla projects are moving away from django-nose, which means that work will have to move to nights and weekends, for even less attention and slower releases.
4. Built-in features like `REUSE_DB=1` are [flaky](https://github.com/django-nose/django-nose/milestones/Fix%20REUSE_DB=1) and not used by everyone. This means that patches work for some people and not for others. These features require the collaboration of the users of the features, and rapid iteration through possible code changes to get to a shared solution.  Since I don't use these optional features, I can't really judge the PRs we do get.

By moving to jazzband, we'll make it easier for contributors to merge changes and make official releases. In the best case, this will spark some additional contribution to fix long broken features. In the worst case, the people that really need support for the latest Django will be able to publish a compatible version.

To move to jazzband, we'll have to follow the [guidelines](https://jazzband.co/about/guidelines). I think we're pretty close, but will need some changes, such as updating our `CONTRIBUTING.rst`.

I'm looking for feedback from existing maintainers ( @jbalogh , @erikrose, @jsocol, @robhudson ), as well as those who rely on django-nose. If you stay silent, I'm assuming you are OK with the changes needed.

**Comment by jsocol** [comment]
As a maintainer, I'm 👍 —I haven't been an active maintainer for a while. I thought it was © Mozilla, but it looks like it's © @jbalogh, so it's probably up to him, with some level of sign-off from the Moz folks.

**Comment by jwhitlock** [comment]
I was doing my periodic refresh of this project, and I wanted to go ahead and make the move to Jazzband. I think we already fit most of the [guidelines](https://jazzband.co/about/guidelines), and PR #301 updates the docs as needed.

@jezdez, I'm planning on moving the project later this week, please let me know if you think it isn't appropriate for Jazzband, or if there are changes you'd expect before the move.

**Comment by jezdez** [comment]
@jwhitlock It's absolutely appropriate! Once you've transferred the repo, a TODO issue is automatically opened to track the rest of the process.

**Comment by jwhitlock** [comment]
Thanks @jezdez! I've transferred the project, it has moved from https://github.com/django-nose/django-nose to https://github.com/jazzband/django-nose

![Jazzband logo](https://jazzband.co/static/img/jazzband.svg)

**Comment by jsocol** [comment]
🙌

**Comment by jezdez** [comment]
Tracking process to adopt Jazzband guidelines: https://github.com/jazzband/roadies/issues/154
