### ISSUE TITLE
Remove me as PyPI owner

### ISSUE THREAD

**Issue by jsocol** [jazzband/django-nose#304]
👋 howdy all

I definitely support the move into jazzband! Along with that, it seems like a good time for me to step off the PyPI maintainer list. I can't remove myself (`jsocol`) but if @jwhitlock or @erikrose wouldn't mind, I certainly would be happy to give up those keys.

**Comment by jwhitlock** [comment]
Thanks @jsocol, I've removed you from the PyPI owners.

**Comment by jsocol** [comment]
Thanks, @jwhitlock!
