### ISSUE TITLE
Add django-nose and nose status to the README

### ISSUE THREAD

**Issue by jwhitlock** [jazzband/django-nose#310]
The [nose docs](https://nose.readthedocs.io/en/latest/) have this note:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using [Nose2](https://github.com/nose-devs/nose2), [py.test](http://pytest.org/), or just plain unittest/unittest2.

I think this project should have a similar note about the status of ``django-nose``.

Personally, I no longer use ``django-nose`` on my work projects (I'm a happy convert to [pytest](http://pytest.org/)), which means I do not have a working project for testing the project, finding issues, and confirming changes. In addition, I've had less and less time and energy for the work of open source maintenance. I'm sorry that this has impacted this project. 

My hope with migrating to jazzband is that it would be easier for the users of the project to identify themselves and take over maintenance. I think a clear statement in the project README would help this along.

Here's my first draft:

# Note to users:

[Nose](https://nose.readthedocs.io/en/latest/) has been in maintenance mode since at least 2015. `django-nose` is in maintenance mode as well, and the sole maintainer is no longer an active user. See [https://jazzband.co](jazzband.co) to learn how `django-nose` is maintained and how you can help. New projects should consider using [py.test](http://pytest.org/), or [unittest](https://docs.python.org/3/library/unittest.html) with the [Django testing framework](https://docs.djangoproject.com/en/3.1/topics/testing/).

**Comment by jayvdb** [comment]
Have we considered asking nose-dev if they would let jazzband assist with maintenance of nose ?

**Comment by jwhitlock** [comment]
> Have we considered asking nose-dev if they would let jazzband assist with maintenance of nose ?

I have not. If you'd like to propose it, then I think you should open an issue on https://github.com/nose-devs/nose or https://github.com/nose-devs/nose2 .
