### ISSUE TITLE
Adopt tox-travis

### ISSUE THREAD

**Issue by jwhitlock** [jazzband/django-nose#316]
[tox-travis](https://github.com/tox-dev/tox-travis) is a plugin for ``tox`` that simplifies the setup between tox and Travis. For simpler projects, it makes it trivial to test against various Python versions. The ``django-nose`` configuration is more complex:

* Test each Django release
  * Against each supported Python version
    * And each combo of SQLite, MySQL, and PostgreSQL

This may be possible with the [Advanced Configuration](https://tox-travis.readthedocs.io/en/stable/envlist.html#advanced-configuration).

The alternative, of a carefully constructed test matrix in ``.travis.yml``, is repetitive, yet error prone when dropping or adding support, versus the ``tox`` notation for specifying variants:

https://github.com/jazzband/django-nose/blob/c48bd0e6b8e0f4c25af17feb83f1f06f3ce0254e/tox.ini#L1-L10

**Comment by jezdez** [comment]
This is moot due to #317 which also used tox-gh-actions.
