### ISSUE TITLE
django-nose cannot find any test

### ISSUE THREAD

**Issue by adilet-web-dev** [jazzband/django-nose#321]
when I run `manage.py test` it runs zero tests
`
nosetests --verbosity=1
Creating test database for alias 'default'...

----------------------------------------------------------------------
Ran 0 tests in 0.000s
`
 even if without Django-nose Django finds and run them

Django version: 3.2.7 python version: 3.9.2

**Comment by Rotzbua** [comment]
`django-nose` is deprecated anyway and should be replaced https://github.com/jazzband/django-nose#note-to-users .
It also breaks with python 3.10.
